version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: intern_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: intern_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: intern_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/intern_project
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=docker_super_secret_jwt_key
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost:3000
      - API_URL=http://localhost:5000/api/v1
    depends_on:
      - mongodb
      - redis

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:5000/api/v1
    container_name: intern_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data: